# coding: utf-8

# flake8: noqa

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.address import Address
from openapi_client.models.error_info import ErrorInfo
from openapi_client.models.error_info_error_code import ErrorInfoErrorCode
from openapi_client.models.get_parcel_list_request import GetParcelListRequest
from openapi_client.models.get_parcel_list_response import GetParcelListResponse
from openapi_client.models.get_parcel_statuses_request import GetParcelStatusesRequest
from openapi_client.models.get_parcel_statuses_response import GetParcelStatusesResponse
from openapi_client.models.get_printed_labels_request import GetPrintedLabelsRequest
from openapi_client.models.get_printed_labels_response import GetPrintedLabelsResponse
from openapi_client.models.parcel import Parcel
from openapi_client.models.parcel_info import ParcelInfo
from openapi_client.models.parcel_status import ParcelStatus
from openapi_client.models.prepare_labels_request import PrepareLabelsRequest
from openapi_client.models.prepare_labels_response import PrepareLabelsResponse
from openapi_client.models.print_data_info import PrintDataInfo
from openapi_client.models.print_labels_request import PrintLabelsRequest
from openapi_client.models.print_labels_response import PrintLabelsResponse
from openapi_client.models.service import Service
