# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Address(BaseModel):
    """
    Address
    """ # noqa: E501
    name: Optional[StrictStr] = Field(default=None, alias="Name")
    street: Optional[StrictStr] = Field(default=None, alias="Street")
    house_number: Optional[StrictStr] = Field(default=None, alias="HouseNumber")
    house_number_info: Optional[StrictStr] = Field(default=None, alias="HouseNumberInfo")
    city: Optional[StrictStr] = Field(default=None, alias="City")
    zip_code: Optional[StrictStr] = Field(default=None, alias="ZipCode")
    country_iso_code: Optional[StrictStr] = Field(default=None, alias="CountryIsoCode")
    contact_name: Optional[StrictStr] = Field(default=None, alias="ContactName")
    contact_phone: Optional[StrictStr] = Field(default=None, alias="ContactPhone")
    contact_email: Optional[StrictStr] = Field(default=None, alias="ContactEmail")
    __properties: ClassVar[List[str]] = ["Name", "Street", "HouseNumber", "HouseNumberInfo", "City", "ZipCode", "CountryIsoCode", "ContactName", "ContactPhone", "ContactEmail"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Address from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Address from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Name": obj.get("Name"),
            "Street": obj.get("Street"),
            "HouseNumber": obj.get("HouseNumber"),
            "HouseNumberInfo": obj.get("HouseNumberInfo"),
            "City": obj.get("City"),
            "ZipCode": obj.get("ZipCode"),
            "CountryIsoCode": obj.get("CountryIsoCode"),
            "ContactName": obj.get("ContactName"),
            "ContactPhone": obj.get("ContactPhone"),
            "ContactEmail": obj.get("ContactEmail")
        })
        return _obj


