# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.error_info import ErrorInfo
from openapi_client.models.parcel_status import ParcelStatus
from typing import Optional, Set
from typing_extensions import Self

class GetParcelStatusesResponse(BaseModel):
    """
    GetParcelStatusesResponse
    """ # noqa: E501
    client_reference: Optional[StrictStr] = Field(default=None, alias="ClientReference")
    delivery_country_code: Optional[StrictStr] = Field(default=None, alias="DeliveryCountryCode")
    delivery_zip_code: Optional[StrictStr] = Field(default=None, alias="DeliveryZipCode")
    get_parcel_status_errors: Optional[List[ErrorInfo]] = Field(default=None, alias="GetParcelStatusErrors")
    parcel_number: Optional[StrictInt] = Field(default=None, alias="ParcelNumber")
    parcel_status_list: Optional[List[ParcelStatus]] = Field(default=None, alias="ParcelStatusList")
    pod: Optional[List[StrictInt]] = Field(default=None, alias="POD")
    weight: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="Weight")
    __properties: ClassVar[List[str]] = ["ClientReference", "DeliveryCountryCode", "DeliveryZipCode", "GetParcelStatusErrors", "ParcelNumber", "ParcelStatusList", "POD", "Weight"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetParcelStatusesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in get_parcel_status_errors (list)
        _items = []
        if self.get_parcel_status_errors:
            for _item_get_parcel_status_errors in self.get_parcel_status_errors:
                if _item_get_parcel_status_errors:
                    _items.append(_item_get_parcel_status_errors.to_dict())
            _dict['GetParcelStatusErrors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in parcel_status_list (list)
        _items = []
        if self.parcel_status_list:
            for _item_parcel_status_list in self.parcel_status_list:
                if _item_parcel_status_list:
                    _items.append(_item_parcel_status_list.to_dict())
            _dict['ParcelStatusList'] = _items
        # set to None if client_reference (nullable) is None
        # and model_fields_set contains the field
        if self.client_reference is None and "client_reference" in self.model_fields_set:
            _dict['ClientReference'] = None

        # set to None if delivery_country_code (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_country_code is None and "delivery_country_code" in self.model_fields_set:
            _dict['DeliveryCountryCode'] = None

        # set to None if delivery_zip_code (nullable) is None
        # and model_fields_set contains the field
        if self.delivery_zip_code is None and "delivery_zip_code" in self.model_fields_set:
            _dict['DeliveryZipCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetParcelStatusesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ClientReference": obj.get("ClientReference"),
            "DeliveryCountryCode": obj.get("DeliveryCountryCode"),
            "DeliveryZipCode": obj.get("DeliveryZipCode"),
            "GetParcelStatusErrors": [ErrorInfo.from_dict(_item) for _item in obj["GetParcelStatusErrors"]] if obj.get("GetParcelStatusErrors") is not None else None,
            "ParcelNumber": obj.get("ParcelNumber"),
            "ParcelStatusList": [ParcelStatus.from_dict(_item) for _item in obj["ParcelStatusList"]] if obj.get("ParcelStatusList") is not None else None,
            "POD": obj.get("POD"),
            "Weight": obj.get("Weight")
        })
        return _obj


