# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.error_info import ErrorInfo
from openapi_client.models.parcel_info import ParcelInfo
from typing import Optional, Set
from typing_extensions import Self

class PrintLabelsResponse(BaseModel):
    """
    PrintLabelsResponse
    """ # noqa: E501
    labels: Optional[List[StrictInt]] = Field(default=None, alias="Labels")
    print_labels_error_list: Optional[List[ErrorInfo]] = Field(default=None, alias="PrintLabelsErrorList")
    print_labels_info_list: Optional[List[ParcelInfo]] = Field(default=None, alias="PrintLabelsInfoList")
    __properties: ClassVar[List[str]] = ["Labels", "PrintLabelsErrorList", "PrintLabelsInfoList"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PrintLabelsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in print_labels_error_list (list)
        _items = []
        if self.print_labels_error_list:
            for _item_print_labels_error_list in self.print_labels_error_list:
                if _item_print_labels_error_list:
                    _items.append(_item_print_labels_error_list.to_dict())
            _dict['PrintLabelsErrorList'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in print_labels_info_list (list)
        _items = []
        if self.print_labels_info_list:
            for _item_print_labels_info_list in self.print_labels_info_list:
                if _item_print_labels_info_list:
                    _items.append(_item_print_labels_info_list.to_dict())
            _dict['PrintLabelsInfoList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PrintLabelsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Labels": obj.get("Labels"),
            "PrintLabelsErrorList": [ErrorInfo.from_dict(_item) for _item in obj["PrintLabelsErrorList"]] if obj.get("PrintLabelsErrorList") is not None else None,
            "PrintLabelsInfoList": [ParcelInfo.from_dict(_item) for _item in obj["PrintLabelsInfoList"]] if obj.get("PrintLabelsInfoList") is not None else None
        })
        return _obj


