# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ServiceADRParameter(BaseModel):
    """
    ServiceADRParameter
    """ # noqa: E501
    adr_item_type: Optional[StrictInt] = Field(default=None, alias="AdrItemType")
    amount_unit: Optional[StrictInt] = Field(default=None, alias="AmountUnit")
    inner_count: Optional[StrictInt] = Field(default=None, alias="InnerCount")
    pack_size: Optional[StrictInt] = Field(default=None, alias="PackSize")
    un_number: Optional[StrictInt] = Field(default=None, alias="UnNumber")
    __properties: ClassVar[List[str]] = ["AdrItemType", "AmountUnit", "InnerCount", "PackSize", "UnNumber"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceADRParameter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if adr_item_type (nullable) is None
        # and model_fields_set contains the field
        if self.adr_item_type is None and "adr_item_type" in self.model_fields_set:
            _dict['AdrItemType'] = None

        # set to None if amount_unit (nullable) is None
        # and model_fields_set contains the field
        if self.amount_unit is None and "amount_unit" in self.model_fields_set:
            _dict['AmountUnit'] = None

        # set to None if inner_count (nullable) is None
        # and model_fields_set contains the field
        if self.inner_count is None and "inner_count" in self.model_fields_set:
            _dict['InnerCount'] = None

        # set to None if pack_size (nullable) is None
        # and model_fields_set contains the field
        if self.pack_size is None and "pack_size" in self.model_fields_set:
            _dict['PackSize'] = None

        # set to None if un_number (nullable) is None
        # and model_fields_set contains the field
        if self.un_number is None and "un_number" in self.model_fields_set:
            _dict['UnNumber'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceADRParameter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "AdrItemType": obj.get("AdrItemType"),
            "AmountUnit": obj.get("AmountUnit"),
            "InnerCount": obj.get("InnerCount"),
            "PackSize": obj.get("PackSize"),
            "UnNumber": obj.get("UnNumber")
        })
        return _obj


