# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.error_info_error_code import ErrorInfoErrorCode

class TestErrorInfoErrorCode(unittest.TestCase):
    """ErrorInfoErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorInfoErrorCode:
        """Test ErrorInfoErrorCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorInfoErrorCode`
        """
        model = ErrorInfoErrorCode()
        if include_optional:
            return ErrorInfoErrorCode(
            )
        else:
            return ErrorInfoErrorCode(
        )
        """

    def testErrorInfoErrorCode(self):
        """Test ErrorInfoErrorCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
