# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_parcel_list_response import GetParcelListResponse

class TestGetParcelListResponse(unittest.TestCase):
    """GetParcelListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetParcelListResponse:
        """Test GetParcelListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetParcelListResponse`
        """
        model = GetParcelListResponse()
        if include_optional:
            return GetParcelListResponse(
                get_parcel_list_errors = [
                    openapi_client.models.error_info.ErrorInfo(
                        error_code = 56, 
                        error_description = '', 
                        client_reference_list = [
                            ''
                            ], 
                        parcel_id_list = [
                            56
                            ], )
                    ],
                print_data_info_list = [
                    openapi_client.models.print_data_info.PrintDataInfo(
                        client_reference = '', 
                        parcel_id = 56, )
                    ]
            )
        else:
            return GetParcelListResponse(
        )
        """

    def testGetParcelListResponse(self):
        """Test GetParcelListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
