# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_psd_parameter import ServicePSDParameter

class TestServicePSDParameter(unittest.TestCase):
    """ServicePSDParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServicePSDParameter:
        """Test ServicePSDParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServicePSDParameter`
        """
        model = ServicePSDParameter()
        if include_optional:
            return ServicePSDParameter(
                string_value = ''
            )
        else:
            return ServicePSDParameter(
        )
        """

    def testServicePSDParameter(self):
        """Test ServicePSDParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
