# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_adr_parameter import ServiceADRParameter

class TestServiceADRParameter(unittest.TestCase):
    """ServiceADRParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceADRParameter:
        """Test ServiceADRParameter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceADRParameter`
        """
        model = ServiceADRParameter()
        if include_optional:
            return ServiceADRParameter(
                adr_item_type = 56,
                amount_unit = 56,
                inner_count = 56,
                pack_size = 56,
                un_number = 56
            )
        else:
            return ServiceADRParameter(
        )
        """

    def testServiceADRParameter(self):
        """Test ServiceADRParameter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
