# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_parcel_statuses_response import GetParcelStatusesResponse

class TestGetParcelStatusesResponse(unittest.TestCase):
    """GetParcelStatusesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetParcelStatusesResponse:
        """Test GetParcelStatusesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetParcelStatusesResponse`
        """
        model = GetParcelStatusesResponse()
        if include_optional:
            return GetParcelStatusesResponse(
                client_reference = '',
                delivery_country_code = '',
                delivery_zip_code = '',
                get_parcel_status_errors = [
                    openapi_client.models.error_info.ErrorInfo(
                        error_code = null, 
                        error_description = '', 
                        client_reference_list = [
                            ''
                            ], 
                        parcel_id_list = [
                            56
                            ], )
                    ],
                parcel_number = 56,
                parcel_status_list = [
                    openapi_client.models.parcel_status.ParcelStatus(
                        depot_city = '', 
                        depot_number = '', 
                        status_code = '', 
                        status_date = null, 
                        status_description = '', 
                        status_info = '', )
                    ],
                pod = [
                    56
                    ],
                weight = 1.337
            )
        else:
            return GetParcelStatusesResponse(
        )
        """

    def testGetParcelStatusesResponse(self):
        """Test GetParcelStatusesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
