# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prepare_labels_request import PrepareLabelsRequest

class TestPrepareLabelsRequest(unittest.TestCase):
    """PrepareLabelsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrepareLabelsRequest:
        """Test PrepareLabelsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareLabelsRequest`
        """
        model = PrepareLabelsRequest()
        if include_optional:
            return PrepareLabelsRequest(
                parcels = [
                    openapi_client.models.parcel.Parcel(
                        parcel_number = '', 
                        weight = 1.337, 
                        address = openapi_client.models.address.Address(
                            street = '', 
                            city = '', 
                            postal_code = '', 
                            country = '', ), )
                    ]
            )
        else:
            return PrepareLabelsRequest(
        )
        """

    def testPrepareLabelsRequest(self):
        """Test PrepareLabelsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
