# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prepare_labels_response import PrepareLabelsResponse

class TestPrepareLabelsResponse(unittest.TestCase):
    """PrepareLabelsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrepareLabelsResponse:
        """Test PrepareLabelsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrepareLabelsResponse`
        """
        model = PrepareLabelsResponse()
        if include_optional:
            return PrepareLabelsResponse(
                parcel_info_list = [
                    openapi_client.models.parcel_info.ParcelInfo(
                        client_reference = '', 
                        parcel_id = 56, )
                    ],
                prepare_labels_error = [
                    openapi_client.models.error_info.ErrorInfo(
                        error_code = null, 
                        error_description = '', 
                        client_reference_list = [
                            ''
                            ], 
                        parcel_id_list = [
                            56
                            ], )
                    ]
            )
        else:
            return PrepareLabelsResponse(
        )
        """

    def testPrepareLabelsResponse(self):
        """Test PrepareLabelsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
