# coding: utf-8

"""
    MyGLS API

    API for MyGLS services

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.print_labels_response import PrintLabelsResponse

class TestPrintLabelsResponse(unittest.TestCase):
    """PrintLabelsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrintLabelsResponse:
        """Test PrintLabelsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrintLabelsResponse`
        """
        model = PrintLabelsResponse()
        if include_optional:
            return PrintLabelsResponse(
                labels = [
                    56
                    ],
                print_labels_error_list = [
                    openapi_client.models.error_info.ErrorInfo(
                        error_code = null, 
                        error_description = '', 
                        client_reference_list = [
                            ''
                            ], 
                        parcel_id_list = [
                            56
                            ], )
                    ],
                print_labels_info_list = [
                    openapi_client.models.parcel_info.ParcelInfo(
                        client_reference = '', 
                        parcel_id = 56, )
                    ]
            )
        else:
            return PrintLabelsResponse(
        )
        """

    def testPrintLabelsResponse(self):
        """Test PrintLabelsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
